---
output:
  word_document: default
  pdf_document: default
  html_document:
    css: min.css
    highlight: textmate
    theme: null
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(prompt = FALSE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(cache = FALSE)
knitr::opts_chunk$set(fig.width = 10)
knitr::opts_chunk$set(fig.height = 4)
knitr::opts_chunk$set(comment = NA)
knitr::opts_knit$set(root.dir = 'C:/Users/Documents/R/Project')
```

```{r packages, echo=FALSE, results='hide'}
list.packages = c("elasticnet", "lars", "MASS", "pls", "ggplot2", "mlbench", "lattice", "car", "knitr", "caret", "e1071", "DT", "gplots", "ROCR", "klaR", "corrplot", "AppliedPredictiveModeling", "data.table", "kableExtra", "VIM", "Amelia", "earth", "kernlab", "nnet", "mlbench", "plotmo", 'pROC', 'mda')
list.packages = unique(list.packages)
install.pack = list.packages %in% installed.packages()
if(length(list.packages[!install.pack]) > 0) 
  install.p = install.packages(list.packages[!install.pack])
lapply(list.packages, require, character.only=TRUE)
rm(list.packages, install.pack)
```

##Data:
```{r data}
setwd('C:/Users/Documents/R/Project')
sick = read.csv('sick_final_.txt')
y = sick['class_sick']$class_sick
y = as.character(y)
y[y==1] = "Yes"
y[y==0] = "No"
y = factor(y, levels=c("Yes","No"))
data = sick[, -grep('class_sick', colnames(sick))]
train_ind = createDataPartition(y, p=0.8, list=F)
```

##my_model:
```{r my_model_}
ctrl = trainControl(method="LGOCV", summaryFunction=defaultSummary, classProbs=TRUE,
                     savePredictions=TRUE, number=5)
zeroVar = nearZeroVar(data)
length(zeroVar)
data = data[ , -zeroVar]
train = data[train_ind, ]
test = data[-train_ind, ]
y_train = y[train_ind]
y_test = y[-train_ind]
```

```{r dist_responseVar}
par(mfrow=c(1,2))
tb_all = table(y)/length(y)
xlab_all = paste0('Yes = ', round(tb_all[1]*100, 2), '%, No = ', round(tb_all[2]*100, 2), '%')
barchart(table(y), horizontal = F, main='Distribution of Sick before splitting', xlab = xlab_all)

tb_tr = table(y_train)/length(y_train)
xlab = paste0('Yes = ', round(tb_tr[1]*100, 2), '%, No = ', round(tb_tr[2]*100, 2), '%')
barchart(table(y_train), horizontal = F, main='Distribution of Sick in Train', xlab = xlab)
tb_te = table(y_test)/length(y_test)
xlab_te = paste0('Yes = ', round(tb_te[1]*100, 2), '%, No = ', round(tb_te[2]*100, 2), '%')
barchart(table(y_test), horizontal = F, main='Distribution of Sick in Test', xlab=xlab_te)
```

```{r MDA}
rm(my_model, my_Roc, y_pred, my_Roc_test, y_pr)
cat('#### Mixture Discriminant Analysis ####')
set.seed(1)
my_model <- train(train, y=y_train, method="mda", tuneGrid=expand.grid(subclasses=1:10), 
                  metric="Kappa", trControl=ctrl)
my_model
plot(my_model)
confusionMatrix(data=my_model$pred$pred, reference=my_model$pred$obs)
important_var <- caret::varImp(my_model) 
important_var
plot(important_var)

#prediction
cat('Summary Analysis of - Testing')
y_pr = predict(my_model, newdata=test)
confusionMatrix(data=y_pr, reference=y_test)
```

```{r RDA}
rm(my_model, my_Roc, y_pred, my_Roc_test, y_pr)
cat('#### Regularized Discriminant Analysis ####')
set.seed(1)
grid <- expand.grid(.gamma = seq(0.1, 1, length = 10), .lambda = seq(0, 1, length = 10))
my_model <- train(train, y=y_train, method="rda", 
                  tuneGrid=grid, metric="Kappa", trControl=ctrl, preProc=c('center', 'scale'))
my_model
plot(my_model)
confusionMatrix(data=my_model$pred$pred, reference=my_model$pred$obs)
important_var <- caret::varImp(my_model) 
important_var
plot(important_var)

#prediction
cat('Summary Analysis of - Testing')
y_pr = predict(my_model, newdata=test)
confusionMatrix(data=y_pr, reference=y_test)
```

```{r FDA}
rm(my_model, my_Roc, y_pred, my_Roc_test, y_pr)
cat('#### Flexible Discriminant Analysis ####')
set.seed(1)
marsGrid <- expand.grid(.degree = 1:3, .nprune = 2:13)
my_model <- train(train, y=y_train, method="fda", 
                  tuneGrid=marsGrid, metric="Kappa", trControl=ctrl, preProc=c('center', 'scale'))
my_model
plot(my_model)
confusionMatrix(data=my_model$pred$pred, reference=my_model$pred$obs)
important_var <- caret::varImp(my_model) 
important_var
plot(important_var)

#prediction
cat('Summary Analysis of - Testing')
y_pr = predict(my_model, newdata=test)
confusionMatrix(data=y_pr, reference=y_test)
```

```{r SVM_Radial}
rm(my_model, my_Roc, y_pred, my_Roc_test, y_pr)
cat('#### SVM Radial ####')
set.seed(1)
sigmaEst = kernlab::sigest(as.matrix(train))
svagrid = expand.grid(sigma=sigmaEst[1], C=2^seq(-6, +6))
my_model <- train(train, y=y_train, method="svmRadial", metric="Kappa", trControl=ctrl,
                  preProc=c('center', 'scale'), fit=FALSE, tuneGrid = svagrid)
my_model
plot(my_model)
confusionMatrix(data=my_model$pred$pred, reference=my_model$pred$obs)
important_var <- caret::varImp(my_model) 
important_var
plot(important_var)

#prediction
cat('Summary Analysis of - Testing')
y_pr = predict(my_model, newdata=test)
confusionMatrix(data=y_pr, reference=y_test)
```

```{r SVM_Polynomial}
rm(my_model, my_Roc, y_pred, my_Roc_test, y_pr)
cat('#### SVM Polynomial ####')
set.seed(1)
poly_grid = expand.grid(degree = c(2, 3, 4), C = 2^seq(-6, 6, length = 13), scale = c(.5, .1, 0.01))
my_model <- train(train, y=y_train, method="svmPoly", metric="Kappa", trControl=ctrl,
                  preProc=c('center', 'scale'), fit=FALSE, tuneGrid = poly_grid)
my_model
plot(my_model)
confusionMatrix(data=my_model$pred$pred, reference=my_model$pred$obs)
important_var <- caret::varImp(my_model) 
important_var
plot(important_var)

#prediction
cat('Summary Analysis of - Testing')
y_pr = predict(my_model, newdata=test)
confusionMatrix(data=y_pr, reference=y_test)
```

```{r NNET}
rm(my_model, my_Roc, y_pred, my_Roc_test, y_pr)
cat('#### Neural Network  ####')
set.seed(1)
nnetGrid = expand.grid(.size=1:10, .decay=c(0, 0.1, 1, 2))

my_model = train(x = train, y=y_train, method="nnet", metric="Kappa",
            preProc=c("center","scale","spatialSign"), tuneGrid=nnetGrid, trace=FALSE,
            maxit=3000, trControl=ctrl)

my_model
plot(my_model)
confusionMatrix(data=my_model$pred$pred, reference=my_model$pred$obs)
important_var <- caret::varImp(my_model) 
important_var
plot(important_var)

#prediction
cat('Summary Analysis of - Testing')
y_pr = predict(my_model, newdata=test)
confusionMatrix(data=y_pr, reference=y_test)
```

```{r KNN}
rm(my_model, my_Roc, y_pred, my_Roc_test, y_pr)
cat('#### KNN ####')
set.seed(1)
knngrid = data.frame(.k = seq(1, 101, by = 2))
my_model <- train(train, y=y_train, method="knn", tuneGrid = knngrid, preProc=c("center","scale"), metric="Kappa", trControl=ctrl)
my_model
plot(my_model)
confusionMatrix(data=my_model$pred$pred, reference=my_model$pred$obs)
important_var <- caret::varImp(my_model) 
important_var
plot(important_var)

#prediction
cat('Summary Analysis of - Testing')
y_pr = predict(my_model, newdata=test)
confusionMatrix(data=y_pr, reference=y_test)
```

```{r NB}
rm(my_model, my_Roc, y_pred, my_Roc_test, y_pr)
cat('#### Naive Bayes ####')
set.seed(1)
nbgrid = expand.grid(.fL = 0, .usekernel=TRUE, .adjust=1:10)
my_model <- train(train, y=y_train, method="nb", metric="Kappa", trControl=ctrl, tuneGrid=nbgrid)
my_model
plot(my_model)
confusionMatrix(data=my_model$pred$pred, reference=my_model$pred$obs)
important_var <- caret::varImp(my_model) 
important_var
plot(important_var)

#prediction
cat('Summary Analysis of - Testing')
y_pr = predict(my_model, newdata=test)
confusionMatrix(data=y_pr, reference=y_test)
```





