---
title: "Preprocessing"
author: "Ibrahim"
date: '`r Sys.Date()`'
output:
word_document: default
html_document:
css: min.css
highlight: textmate
theme: null
pdf_document: default
editor_options:
  chunk_output_type: console
chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(prompt = FALSE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(cache = FALSE)
knitr::opts_chunk$set(fig.width = 6)
knitr::opts_chunk$set(fig.height = 6)
knitr::opts_knit$set(root.dir = 'C:/Users/Documents/R/Project')
```

```{r packages, echo=FALSE, results='hide'}
list.packages = c("ggplot2", "mlbench", "lattice", "car", "knitr", "caret", "e1071", "DT", "gplots", "ROCR", "klaR", "corrplot",
"AppliedPredictiveModeling", "data.table", "plotly", "VIM", "Amelia")
list.packages = unique(list.packages)
install.pack = list.packages %in% installed.packages()
if(length(list.packages[!install.pack]) > 0)
install.p = install.packages(list.packages[!install.pack])
lapply(list.packages, require, character.only=TRUE)
rm(install.pack, list.packages)
```

```{r myFunctions, echo=FALSE, results='hide'}
#for multiple density plot #the data should be melt.
my_densityplot = function(meltData)
{
    densityplot(~value|variable, data = meltData, scales = list(x = list(relation = "free"), y = list(relation = "free")), 
                adjust = 1.25, pch= "|", xlab = "Predictor")
}

my_densityplot_2 = function(meltData, xlab)
{
    densityplot(~value|variable, data = meltData, scales = list(x = list(relation = "free"), 
                y = list(relation = "free")), adjust = 1.25, pch= "|", xlab = xlab)
}

#for multiple histogram #the data should be melt
my_multipleHistogram = function(meltData, bins)
{
    ggplot(data = melt(meltData), mapping = aes(x = value)) + geom_histogram(bins = bins) + 
    facet_wrap(~variable, scales ='free_x')
}

#for multiple correlation plots with correlation coefficient & p-value calculation
panel.cor <- function(x, y, digits = 2, cex.cor, ...)
{
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(0, 1, 0, 1))
  # correlation coefficient
  r <- cor(x, y)
  txt <- format(c(r, 0.123456789), digits = digits)[1]
  txt <- paste("r= ", txt, sep = "")
  text(0.5, 0.6, txt)
  # p-value calculation
  p <- cor.test(x, y)$p.value
  txt2 <- format(c(p, 0.123456789), digits = digits)[1]
  txt2 <- paste("p= ", txt2, sep = "")
  if(p<0.01) txt2 <- paste("p= ", "<0.01", sep = "")
  text(0.5, 0.4, txt2)
}
```

##data preprocessing
```{r load_downloaded}
setwd('C:/Users/Documents/R/Project')
sick = read.csv('sick_original.txt')
#clean the class (remove the index attached)
sick$class = data.frame(do.call('rbind', strsplit(as.character(sick$class), '.' ,fixed=TRUE)))[ ,1]
sick[sick == '?'] = NA #replace ? with NA
aggr(sick, prop = T, numbers = T, col='#756bb1')
missmap(sick, col=c("black", "#756bb1"), legend=FALSE)
#All values in Predictor TBG are missing, hence we will drop it
sick = sick[, -28]
missingValue_meth = TRUE
ind_measured_var = grep('measured', names(sick))
sick = sick[-ind_measured_var]
```

```{r knn_impute_or_removemissing}
if(missingValue_meth)
{
sick_compl = kNN(sick, imp_var = FALSE)
}else
{
missing = unlist(lapply(sick, function(x) any(is.na(x))))
missing = names(missing)[missing]
sick_miss = sick[missing]
sick_compl = sick[complete.cases(sick), ]
orig = table(sick$class) / sum(table(sick$class))
new = table(sick_compl$class) / sum(table(sick_compl$class))
perc_missing = (orig[1] - new[1]) / orig[1]
cat('The percentage of the missing values is', paste0(round(perc_missing, 2) * 100, '%'))
par(mfrow = c(1, 2))
col = c('#756bb1', '#bcbddc')
xlab = paste0('The original dataset - ', round(orig[1] * 100, 1), ' negative class')
barplot(orig, main='Class label', col=col, xlab=xlab, ylab='% Distribution')
xlab = paste0('After removing missing values - ', round(new[1] * 100, 1), ' sick class')
barplot(new, col=col, xlab=xlab, ylab='% Distribution')
}
missmap(sick_compl, col=c("black", "#756bb1"), legend=FALSE)
```

```{r get_categorical_continuous}
sick = sick_compl
sick$age = as.numeric(sick$age)
sick$TSH = as.numeric(sick$TSH)
sick$T3 = as.numeric(sick$T3)
sick$TT4 = as.numeric(sick$TT4)
sick$T4U = as.numeric(sick$T4U)
sick$FTI = as.numeric(sick$FTI)
categ_var = sapply(sick, is.factor)
categ_var = colnames(sick)[categ_var]
num_var = sapply(sick, is.numeric)
num_var = colnames(sick)[num_var]
```

```{r class_distribution}
orig = table(sick$class) / sum(table(sick$class))
par(mfrow = c(1, 1))
col = c('#756bb1', '#bcbddc')
xlab = paste0('The original dataset - ', round(orig[1] * 100, 1), ' negative class')
barplot(orig, main='Class label', col=col, xlab=xlab, ylab='% Distribution')
```

```{r frequency_dist_categorical,fig.height=10, fig.width=10}
clas_ind = grep('class', colnames(sick))
par(mfrow = c(4, 3))
ind_cat = grep('class', categ_var)
var = categ_var[-ind_cat]
cat('Frequency Distribution of Categorical Predictors:')
for (i in var)
{
col = c('#756bb1', '#bcbddc')
dt = table(sick[[i]], exclude = '?')
row_sub = apply(dt, 1, function(row) all(row !=0 ))
dt = dt[row_sub]
if(identical(i, 'referralsource'))
col = c('#ffffcc', '#a1dab4', '#41b6c4', '#2c7fb8', '#253494')
barplot(dt, col = col, main = i)
}
```

```{r nearZero_categorical}
col_nearzero = nearZeroVar(sick)
names(sick[,col_nearzero])
sick = sick[-col_nearzero]
ncol(sick)
```

```{r histogram_boxplot_densityplot_continuous_predictors}
#The original data contained several "measured" columns which were binary versions of the predictors. TSH_measured,
#T3_measured, TT4_measured, T4U_measured, FTI_measured, and TBG_measured . Thus, they would be irrelevant for
#prediction.
#statusColNum = grep("measured", names(sick)) ## Pattern Matching and Replacement
#sick = sick[, -statusColNum]
#Data source(referralsource) might not affect the preditive models.
#drop_source
#colnum = grep('referralsource', names(sick))
#sick = sick[, -colnum]
#distribution_numerical
cat('Histogram Distribution of Continuous Predictors:')
par(mfrow = c(2, 3))
for (i in num_var)
{
hist(sick[[i]], main = i, col = '#756bb1', xlab = NA)
}
cat('Boxplot of Continuous Predictors:')
par(mfrow = c(2, 3))
for (i in num_var)
{
boxplot(sick[[i]], main = i, col = '#756bb1', xlab = NA)
}
categ_var = sapply(sick, is.factor)
categ_var = colnames(sick)[categ_var]
num_var = sapply(sick, is.numeric)
num_var = colnames(sick)[num_var]
sick_numvar = sick[num_var]
sick_melt = melt(sick_numvar)
cat('Density Plot of Continuous Predictors:')
my_densityplot(sick_melt)
skewValues = apply(sick_numvar, 2, skewness)
skewValues = as.data.frame(skewValues)
skewLevel = c("Symmetric", "Symmetric", "Moderately Skewed", "Symmetric", "Heavily Skewed", "Symmetric")
skewValues[, 2] = skewLevel
colnames(skewValues) = c('Skew Value', 'Skew Level')
kable(skewValues, caption = "Skewness Level of Continuous Predictors")
```

```{r sick_by_source}
sick_other = sick[which(sick$referralsource == 'other'),]
sick_STMW = sick[which(sick$referralsource == 'STMW'),]
sick_SVHC = sick[which(sick$referralsource == 'SVHC'),]
sick_SVHD = sick[which(sick$referralsource == 'SVHD'),]
sick_SVI = sick[which(sick$referralsource == 'SVI'),]
sick_melt = melt(sick_other)
cat('Density Plot of Continuous Predictors by Source: others:')
my_densityplot_2(sick_melt, 'ReferralSource: others')
sick_melt = melt(sick_STMW)
cat('Density Plot of Continuous Predictors by Source: STMW:')
my_densityplot_2(sick_melt, 'ReferralSource: STMW')
sick_melt = melt(sick_SVHC)
cat('Density Plot of Continuous Predictors by Source: SVHC:')
my_densityplot_2(sick_melt, 'ReferralSource: SVHC')
sick_melt = melt(sick_SVHD)
cat('Density Plot of Continuous Predictors by Source: SVHD:')
my_densityplot_2(sick_melt, 'ReferralSource: SVHD')
sick_melt = melt(sick_SVI)
cat('Density Plot of Continuous Predictors by Source: SVI:')
my_densityplot_2(sick_melt, 'ReferralSource: SVI')
```

```{r sick_by_source_density}
continuousVar = function(data, num_var)
{
sick = data
cat('Histogram Distribution of Continuous Predictors:')
par(mfrow = c(2, 3))
for (i in num_var)
{
hist(sick[[i]], main = i, col = '#756bb1', xlab = NA)
}
cat('Boxplot of Continuous Predictors:')
par(mfrow = c(2, 3))
for (i in num_var)
{
boxplot(sick[[i]], main = i, col = '#756bb1', xlab = NA)
}
num_var = sapply(sick, is.numeric)
num_var = colnames(sick)[num_var]
sick_numvar = sick[num_var]
skewValues = apply(sick_numvar, 2, skewness)
skewValues = as.data.frame(skewValues)
skewLevel = c("Symmetric", "Symmetric", "Moderately Skewed", "Symmetric", "Heavily Skewed", "Symmetric")
skewValues[, 2] = skewLevel
colnames(skewValues) = c('Skew Value', 'Skew Level')
kable(skewValues, caption = "Skewness Level of Continuous Predictors")
}
```

```{r dummy_variables_categorical}
#segregating the levels in each of the categorical variable
oldsick = sick
categ_var = sapply(sick, is.factor)
categ_var = colnames(sick)[categ_var]
sick_categ = sick[categ_var]
sick_categ$sex = ifelse(sick$sex == "M", "t", ifelse(sick$sex == "F", "f", -1))
sick_categ = as.data.frame(sapply(sick_categ, factor))
# recoding table, stored in a simple vector
recode <- c(t = 1, f = 0)
recode_dt = data.frame(SN = c(1:nrow(sick_categ)))
for(i in categ_var)
{
  data = sick_categ[[i]]
  for(level in unique(data))
  {
  recode_dt[paste(i, level, sep = "_")] = ifelse(data == level, 1, 0)
  }
}
recode_dt = recode_dt[, -1]
#correlation of the recoded categorical predictors
cat('Head Correlation of Recoded Categorical Predictors:')
#pairs(recode_dt[,1:4], upper.panel = panel.cor)
ind_referral_dummy = grep('referral', names(recode_dt))
ind_keep_class = grep('_sick', names(recode_dt))
ind_keep_t = grep('_t', names(recode_dt))
pairs(recode_dt[ind_referral_dummy], upper.panel = panel.cor)
#drop the extra columns: since we have established that the corresponding columns are correlated
#keep that of referral sources
recode_dt_old = recode_dt
#recode_dt = recode_dt_old
recode_dt = cbind(recode_dt[ind_keep_t], recode_dt[ind_referral_dummy], recode_dt[ind_keep_class])
#names(recode_dt) = names(sick_categ)
sickold = sick

#merge the recoded categorical variables with the continuous variables
sick = cbind(recode_dt, sick_numvar)
clas_ind = grep('class', colnames(sick))
#centring and scaling
sick_centre_scale = scale(sick, center = TRUE, scale = TRUE)
```

```{r correlation_all}
cat("\nCorrelation Plot of data before transformation:")
cor = cor(sick[,-clas_ind])
corrplot(cor, order = "hclust")
#cat("\nCorrelation Plot of the transformed data: Center & Scale Transformation:")
#cor = cor(sick_centre_scale[,-clas_ind])
#corrplot(cor, order = "hclust")
#fine high correlation #Nothing discovered
cat("\nHigh correlation:")
highCorr = findCorrelation(cor, cutoff = .80)
length(highCorr)
sick_final = sick
write.table(sick_final, "C:/Users/2PAC/Documents/R/Predictive_Modeling/Project/sick_final_.txt", sep=",")
```

```{r yeo_johnson}
par(mfrow = c(1, 2))
cor = cor(sick_numvar)
corrplot(cor, order = "hclust")
highCorr = findCorrelation(cor, cutoff = .80)
length(highCorr)
yeo_trans = preProcess(sick_numvar, method = "YeoJohnson")
transformed = predict(yeo_trans, newdata = sick_numvar)
cor = cor(transformed)
corrplot(cor, order = "hclust")
highCorr = findCorrelation(cor, cutoff = .80)
length(highCorr)
par(mfrow = c(1, 2))
sick_melt = melt(sick_numvar)
my_densityplot(sick_melt)
sick_melt = melt(transformed)
my_densityplot(sick_melt)
```

```{r spatial_outliers}
spatialtransformed = spatialSign(sick_numvar)
transformed = as.data.frame(spatialtransformed)
cat('Boxplot After Spatial Sign Transformation:')
par(mfrow = c(2, 3))
for (i in num_var)
{
  boxplot(transformed[[i]], main = i, col = '#756bb1', xlab = NA)
}
```

```{r boxcox_transformation}
trans = preProcess(sick_numvar, method = c("BoxCox", "center", "scale"))
trans
transformed = predict(trans, sick_numvar)
sick_melt = melt(transformed)
my_densityplot(sick_melt)
skewValues = apply(transformed, 2, skewness)
skewValues = as.data.frame(skewValues)
skewLevel = c("Symmetric", "Symmetric", "Symmetric", "Symmetric", "Symmetric", "Symmetric")
skewValues[, 2] = skewLevel
colnames(skewValues) = c('Skew Value', 'Skew Level')
kable(skewValues, caption = "Skewness Level of Continuous Predictors")
dim(transformed)
```

```{r pca}
trans = preProcess(sick, method = c("center", "scale", "pca"))
trans
transformed = predict(trans, sick)
dim(transformed)
```